import { z } from 'zod';
import { defineCapabilityInput, defineCapabilityTool, type CapabilityExecutionContext, type CapabilityHealth, type CapabilityManifest, type CapabilityProvider, type CapabilityRunContext } from '@webpilot/capability-sdk';
import { communicationRuntimeSkill } from './runtime-skill.js'; import { communicationCapabilitySettings } from './settings.js'; export * from './runtime-skill.js'; export * from './settings.js';

export const communicationCapabilityToolNames = Object.freeze({ communication: 'communication' } as const);
export type CommunicationDraft = { id: string; channelId: string; recipients: string[]; subject?: string; body: string; metadata?: Record<string, unknown>; createdAt: string };
export type CommunicationReceipt = { channelId: string; messageId: string; acceptedAt: string; details?: unknown };
export interface CommunicationChannel { id: string; name: string; kind: string; send(draft: CommunicationDraft, context: CapabilityExecutionContext): Promise<CommunicationReceipt>; health?(): Promise<CapabilityHealth>; dispose?(): Promise<void>; }
export interface CommunicationDraftStore { create(input: Omit<CommunicationDraft, 'id' | 'createdAt'>): Promise<CommunicationDraft>; get(id: string): Promise<CommunicationDraft | undefined>; }
export function createMemoryCommunicationDraftStore(): CommunicationDraftStore { const drafts = new Map<string, CommunicationDraft>(); return { async create(input) { const draft = { ...input, id: globalThis.crypto.randomUUID(), createdAt: new Date().toISOString() }; drafts.set(draft.id, draft); return draft; }, async get(id) { return drafts.get(id); } }; }

const parser = z.object({ action: z.enum(['channels', 'draft', 'readDraft', 'send']), reason: z.string().trim().min(1).max(300), channelId: z.string().trim().min(1).max(200).optional(), recipients: z.array(z.string().trim().min(1).max(500)).min(1).max(100).optional(), subject: z.string().trim().max(1_000).optional(), body: z.string().min(1).max(200_000).optional(), metadata: z.record(z.string(), z.unknown()).optional(), draftId: z.string().uuid().optional() }).strict().superRefine((input, context) => { if (input.action === 'draft' && (!input.channelId || !input.recipients?.length || !input.body)) context.addIssue({ code: 'custom', message: 'draft requires channelId, recipients, and body.' }); if ((input.action === 'readDraft' || input.action === 'send') && !input.draftId) context.addIssue({ code: 'custom', path: ['draftId'], message: `${input.action} requires draftId.` }); });
export type CommunicationToolInput = z.infer<typeof parser>; export const communicationToolInput = defineCapabilityInput<CommunicationToolInput>(z.toJSONSchema(parser) as Readonly<Record<string, unknown>>, (value) => parser.parse(value));
export const communicationCapabilityManifest = Object.freeze({ schemaVersion: 1, id: 'com.webpilot.communication', name: 'Communication', version: '0.1.0', description: 'Create drafts and send approved messages through host-configured communication channels.', permissions: ['communication:draft', 'communication:send', 'network:external'], runtimeRequirements: { node: '>=22.16' }, configuration: { settings: communicationCapabilitySettings }, skills: [communicationRuntimeSkill] } satisfies CapabilityManifest);

export function createCommunicationTool(channels: readonly CommunicationChannel[], drafts: CommunicationDraftStore, configuration: CapabilityRunContext['configuration']) { const byId = new Map(channels.map((channel) => [channel.id, channel])); return defineCapabilityTool<CommunicationToolInput, unknown>({
  name: 'communication', description: 'List outbound channels, create/read an exact message draft, or send an existing draft after host approval.', input: communicationToolInput, policy: { concurrency: 'serial', concurrencyGroup: 'outbound-communication', permissions: communicationCapabilityManifest.permissions },
  async execute(input, context) { try { if (input.action === 'channels') return { ok: true, summary: 'Configured communication channels.', data: channels.map(({ id, name, kind }) => ({ id, name, kind })) }; if (input.action === 'draft') { if (!byId.has(input.channelId!)) return { ok: false, error: { code: 'communication-channel-not-found', message: `Unknown channel: ${input.channelId}.` } }; const draft = await drafts.create({ channelId: input.channelId!, recipients: input.recipients!, subject: input.subject, body: input.body!, metadata: input.metadata }); return { ok: true, summary: `Communication draft ${draft.id} created.`, data: draft }; } const draft = await drafts.get(input.draftId!); if (!draft) return { ok: false, error: { code: 'communication-draft-not-found', message: `Unknown draft: ${input.draftId}.` } }; if (input.action === 'readDraft') return { ok: true, summary: `Communication draft ${draft.id}.`, data: draft }; if (configuration.AGENT_COMMUNICATION_ALLOW_SEND !== 'true') return { ok: false, error: { code: 'communication-send-disabled', message: 'Outbound communication is disabled by host configuration.' } }; const channel = byId.get(draft.channelId); if (!channel) return { ok: false, error: { code: 'communication-channel-not-found', message: `Unknown channel: ${draft.channelId}.` } }; const receipt = await channel.send(draft, context); return { ok: true, summary: `Message accepted by ${channel.name}.`, data: receipt }; } catch (error) { return { ok: false, error: { code: 'communication-operation-failed', message: error instanceof Error ? error.message : String(error) } }; } },
}); }
export function createCommunicationCapability(options: { createChannels(context: CapabilityRunContext): readonly CommunicationChannel[] | Promise<readonly CommunicationChannel[]>; createDraftStore?(context: CapabilityRunContext): CommunicationDraftStore | Promise<CommunicationDraftStore> }): CapabilityProvider { return { manifest: communicationCapabilityManifest, async createRuntime(context) { const channels = await options.createChannels(context); const drafts = await options.createDraftStore?.(context) || createMemoryCommunicationDraftStore(); return { tools: Object.freeze({ communication: createCommunicationTool(channels, drafts, context.configuration) }), health: async () => { const statuses = await Promise.all(channels.map((channel) => channel.health?.() || Promise.resolve({ status: 'healthy' as const }))); return statuses.some((item) => item.status === 'unhealthy') ? { status: 'degraded', message: 'One or more communication channels are unhealthy.' } : { status: 'healthy' }; }, dispose: async () => { await Promise.allSettled(channels.map((channel) => channel.dispose?.())); } }; } }; }
