export function domObservationHardRules() {
  return [
    '- If the page may have changed or you need fresh DOM/text evidence, call readObservation({refresh:true,view:"actions",maxChars:10000}) explicitly. The backend will not silently refresh page state between model calls.',
    '- If visual evidence is needed and the configured model supports image input, call getCurrentScreenshot. Screenshot evidence is separate from DOM/action ids.',
    '- In DOM mode, if you cannot confidently identify the target element from readObservation/findByText, call getCurrentScreenshot before deciding the action or declaring the task blocked.',
    '- If text-only DOM evidence is ambiguous because of stacked overlays, date pickers, popovers, duplicated labels, icon-only controls, hidden hover menus, or uncertainty about the active layer, and getCurrentScreenshot is available, call getCurrentScreenshot before choosing an action.',
    '- Prefer readObservation({refresh:true,view:"actions",maxChars:10000}) to refresh page state and read the first lazy DOM slice. If the result has nextCursor, continue with readObservation({cursor:nextCursor,maxChars:10000}). maxChars values below 10000 are raised to 10000.',
  ];
}

export function domModeActionRules() {
  return [
    '- DOM mode readObservation stores lazy observation views generated by the browser DOM runtime: actions, tree, text, and changes.',
    '- For first/normal DOM evidence, call readObservation({refresh:true,view:"actions",maxChars:10000}) to refresh and inspect clickable/fillable node_id entries in one tool call.',
    '- After a browser-changing action, call readObservation({refresh:true,view:"actions",maxChars:10000}) before choosing another DOM action. Use view:"changes" only when you need the refresh-boundary summary.',
    '- Use readObservation with nextCursor to continue parsing the latest lazy observation; do not use offset unless you are reading already stored text.',
    '- For normal DOM-mode clicking/filling/hovering, use clickDomNode/fillDomNodes/hoverDomNode with a fresh node_id from readObservation actions.',
    '- Use findByText(targetText) only as recovery when a node_id target is unavailable; it searches the current observation tree/references and returns node_id values with an interactive flag. Click only interactive=true results with clickDomNode(id,text?).',
    '- For hover-only menus in DOM mode, use current actions node_id evidence to choose a supported hover path, then call readObservation({refresh:true,view:"actions",maxChars:10000}) before choosing a revealed target.',
    '- Use scrollArea only when interaction requires changing the visual viewport or lazy-loaded content is absent from the elements context. After scrolling or any browser-changing action, call readObservation({refresh:true,view:"actions",maxChars:10000}) before using new ids.',
    '- Before scrollArea, check the latest area summary/result: do not scroll down when atBottom or remainingDown=0, and do not scroll up when atTop or remainingUp=0.',
    '- getCurrentScreenshot is read-only visual evidence. Use it to decide which visible target/layer is correct when DOM evidence is hard to interpret; do not use screenshot positions as action ids. Actions still use DOM node_id tools.',
    '- When multiple visible layers contain similar actions such as 确定/取消, use screenshot evidence if available to identify the currently topmost active layer before clicking.',
    '- In DOM mode, ordinary tool visualAfter screenshots are disabled unless DOM screenshot saving is enabled in settings. Normally omit visualAfter; call getCurrentScreenshot only when explicit visual evidence is needed.',
  ];
}

export function domCurrentContextLine(browserChatMode: boolean) {
  return browserChatMode
    ? 'No DOM/page observation or tool result is preloaded in the initial messages. In DOM mode, call readObservation({refresh:true,view:"actions",maxChars:10000}) when fresh URL, tabs, focus, scroll state, DOM snapshot, or page text is needed.'
    : 'No initial DOM page observation is included. Call readObservation({refresh:true,view:"actions",maxChars:10000}) for fresh URL, tabs, focus, scroll state, DOM snapshot, and page text.';
}

export const domNoScreenshotRule = '- No live screenshot image/path is attached automatically. Use readObservation({refresh:true,view:"actions",maxChars:10000}) to collect the browser-generated DOM observation and actionable node_id entries in one call. Continue with nextCursor when more entries are needed; use view:"tree" or view:"text" only when structure or copy is needed. If you cannot confidently find the target from DOM evidence, or text-only DOM evidence is ambiguous because of stacked overlays/date pickers/duplicate labels/icon-only controls/hidden hover menus, and getCurrentScreenshot is available, call it explicitly before choosing an action or declaring the task blocked; actions still use DOM node_id tools.';
