export function domObservationHardRules() {
  return [
    '- If the page may have changed or you need fresh DOM/text evidence, call getPageState explicitly. The backend will not silently refresh page state between model calls.',
    '- If visual evidence is needed and the configured model supports image input, call getCurrentScreenshot. Screenshot evidence is separate from DOM/action ids.',
    '- If text-only DOM evidence is ambiguous because of stacked overlays, date pickers, popovers, duplicated labels, icon-only controls, or uncertainty about the active layer, and getCurrentScreenshot is available, call getCurrentScreenshot before choosing an action.',
    '- Prefer getPageState({ read: { view, offset, maxChars } }) to refresh page state and inline-read one browser-generated view in the same call. The default actions view lists visible actionable node_id entries first; changes compares the previous and current page state; tree gives full hierarchy; text gives visible page copy. maxChars values below 10000 are raised to 10000.',
  ];
}

export function domModeActionRules() {
  return [
    '- DOM mode getPageState stores readObservation views generated by the browser DOM runtime: actions, tree, text, and changes.',
    '- For first/normal DOM evidence, call getPageState({ read: { view: "actions", offset: 0, maxChars: 10000 } }) to refresh and inspect clickable/fillable node_id entries in one tool call.',
    '- After a browser-changing action, call getPageState({ read: { view: "changes", offset: 0, maxChars: 10000 } }) when you need to know what changed before deciding the next step.',
    '- Use readObservation only to page through or switch views for the latest getPageState observation; do not call it immediately after getPageState if the needed view was already returned inline.',
    '- For normal DOM-mode clicking/filling/hovering, use clickDomNode/fillDomNodes/hoverDomNode with a fresh node_id from readObservation actions.',
    '- Use findByText(targetText) only as recovery when a node_id target is unavailable; it searches the current getPageState tree and returns node_id values with an interactive flag. Click only interactive=true results with clickDomNode(id,text?).',
    '- For hover-only menus in DOM mode, use current actions node_id evidence to choose a supported hover path, then call getPageState before choosing a revealed target.',
    '- Use scrollArea only when interaction requires changing the visual viewport or lazy-loaded content is absent from the elements context. After scrolling or any browser-changing action, call getPageState before using new ids.',
    '- Before scrollArea, check the latest area summary/result: do not scroll down when atBottom or remainingDown=0, and do not scroll up when atTop or remainingUp=0.',
    '- getCurrentScreenshot is read-only visual evidence. Do not use screenshot positions as action ids; use DOM node_id tools for actions.',
    '- When multiple visible layers contain similar actions such as 确定/取消, use screenshot evidence if available to identify the currently topmost active layer before clicking.',
    '- In DOM mode, ordinary tool visualAfter screenshots are disabled unless DOM screenshot saving is enabled in settings. Normally omit visualAfter; call getCurrentScreenshot only when explicit visual evidence is needed.',
  ];
}

export function domCurrentContextLine(browserChatMode: boolean) {
  return browserChatMode
    ? 'No DOM/page observation or tool result is preloaded in the initial messages. In DOM mode, call getPageState with read when fresh URL, tabs, focus, scroll state, DOM snapshot, or page text is needed.'
    : 'No initial DOM page observation is included. Call getPageState with read for fresh URL, tabs, focus, scroll state, DOM snapshot, and page text.';
}

export const domNoScreenshotRule = '- No live screenshot image/path is attached automatically. Use getPageState({ read: { view: "actions", offset: 0, maxChars: 10000 } }) to collect the browser-generated DOM observation and actionable node_id entries in one call. Use read.view="changes" to inspect what changed since the previous page state, and read.view="tree" or read.view="text" only when structure or copy is needed. If visual evidence is needed, or text-only DOM evidence is ambiguous because of stacked overlays/date pickers/duplicate labels, and getCurrentScreenshot is available, call it explicitly; actions still use DOM node_id tools.';
