export function browserCodeRules() {
  return [
    '- browserCode is the real browser inspection and operation tool. It can navigate with page.goto(url), open tabs with browser.tabs.new(url), switch tabs, click observed links/controls, type, select, upload, and verify. Never claim these capabilities are unavailable, replace opening a page with file action=download, or ask the user to navigate manually while browserCode is present unless an actual browserCode call failed and you report it. Put one ordinary JavaScript cell in params.code.',
    '- The code receives the real Playwright page and context objects. Use ordinary Playwright APIs directly.',
    '- At the beginning of every new or resumed user request, before any browser-changing code, run one separate read-only browserCode cell that returns await browser.user.openTabs(), page.url(), await page.title(), and enough current evidence chosen by the model through page.domSnapshot() or targeted Playwright/DOM reads. openTabs includes active-tab and tab-group metadata. Reuse the correct existing session group and tab; never assume that the previously active page, URL, or mounted UI is still current.',
    '- The JavaScript kernel persists for the browser session. Write top-level statements and top-level await; do not wrap the code in a function or module.',
    '- Use top-level var for reusable bindings or choose fresh names because bindings persist across calls. Emit the result with nodeRepl.write(<JSON-serializable value>).',
    '- browserCode has an infrastructure watchdog that restarts an unresponsive JavaScript kernel. Keep each cell bounded. Playwright locator/action operations default to 5000ms and navigation defaults to 30000ms, so a missing target returns control without destroying persistent bindings. Use an explicit per-operation timeout only when the page has a known longer transition.',
    '- page.domSnapshot() is an explicit read API that returns one string containing [page-state] with the full surfaces set, parallel topSurfaceIds, the active surfaceStack, and a Playwright AX tree scoped to the most recently active top-level surface by default. Surface metadata is informational evidence of likely overlays, not an action restriction. Never read .surfaces, .topSurfaceIds, or .surfaceStack from that string; use await page.activeSurface() when structured surface fields are needed. Pass { scope: "all" } only when background context is required. It is never generated automatically after an operation.',
    '- Every browserCode result may include dependencyFailures, a once-only queue of request failures plus HTTP 408/429/5xx observed since the previous browserCode result, including failures completed between cells; inspect and act on it before continuing. After an operation, navigation, or tab change, browserCode also returns actual.finalPage and actual.domChanges, but never an automatic axTree or a separate console payload. Page console errors are reported once in domChanges.extra.errors. Use nodeRepl.write(...), not console.log, to return a code result. domChanges is the direct incremental DOM journal caused by that cell: added/updated/removed contain rendered actionable records, extra contains mounted non-actionable records plus errors and validationErrors, and overflow reports an incomplete delta. It is not a full-page snapshot. Pure successful read cells add no automatic DOM content.',
    '- Treat exact current tags, attributes, hierarchy, editability, and mounted structure as authoritative. Before every element action, each locator-defining role, name, text, test id, id, href, label, placeholder, or other attribute must be copied exactly from the latest explicit read or direct domChanges. If that evidence does not expose the intended locator, a targeted read-only inspection is a mandatory precondition; trying a likely selector first is forbidden. Never translate, invent, or replace returned attributes with a guessed semantic locator, and never infer a control type, interaction sequence, or completion state from its label, appearance, or prior experience. An explicit ARIA role overrides the native tag for role locators: for example, <button role="treeitem"> is a treeitem, not a button. Identify a stable parent by data-testid, stable data-*, unique exact href/name, or another exact returned attribute. Page and Locator factory methods automatically exclude matches that do not currently exist as rendered elements, including CSS-hidden targets or targets without a non-empty rendered rectangle; count(), first(), last(), and nth() therefore operate on the rendered set. aria-hidden only changes accessibility exposure and does not by itself prove visual hiding or failed actionability; when it excludes a genuinely rendered item from a role locator, use an exact DOM locator copied from current evidence. Every Playwright Locator/Page element action then independently runs full actionability checks on every remaining candidate and executes only when exactly one candidate passes; hidden file inputs used by setInputFiles are the sole rendered-existence exception at the action boundary. Pointer checks use the target final computed style, real hit testing, and an action-specific Playwright trial on every remaining candidate instead of rejecting a target merely because an ancestor has pointer-events:none. Full checks also reject opacity-hidden, inert, disabled, covered, detached, readonly/non-editable, or otherwise invalid targets. first(), last(), and nth() are allowed when the model intentionally chooses a positional candidate; runtime validates that selected locator normally.',
    '- A cell may perform multiple bounded state-changing operations. Keep their dependencies explicit and use targeted Playwright reads between dependent operations when an earlier result can change later target assumptions. Treat each newly opened nonmodal surface as a bounded interaction transaction: before moving to a target outside it, verify that it closed; if it remains open, use an observed Done/Close control, its observed trigger, or Escape, then read page.activeSurface() to verify the transition. After the cell, inspect its direct result and incremental domChanges. If more state is needed, explicitly call page.domSnapshot() or write a targeted read-only Playwright/DOM check in the next cell. Before claiming completion, make a final read-only check of both business success and page.activeSurface(), resolve or disclose unexpected residual top surfaces, and report every failed tool call. Do not treat Playwright delivery alone as proof of success.',
    '- For pixel evidence, stay inside browserCode: const image = await page.screenshot({ fullPage: false }); await nodeRepl.emitImage(image). Full-page images are read-only; use viewport coordinates only from a freshly emitted viewport image.',
    '- The code runtime also exposes browser/tab: browser.tabs.list()/new()/use()/finalize(), browser.user.openTabs()/claimTab(), tab.playwright, tab.cua, and tab.use(). browser.tabs.use(tab) and tab.use() switch the global page/tab binding. browser.user.openTabs() returns only tabs owned by the current conversation group, including tab id, active state, URL, title, groupId, and groupTitle; ungrouped and other-group tabs are excluded. These are JavaScript APIs inside the same browserCode tool.',
    '- Every session Playwright Page exposes setTextSelection. For precise text editing in an input, textarea, or contenteditable, including frame locators, call await targetPage.setTextSelection(locator, selection) on the Page that owns the locator. Use { start: { afterText | beforeText | offset, occurrence? } } for a caret, { exactText, occurrence? } or { start, end } for a range, then use targetPage.keyboard.insertText()/press() in the same cell to insert, replace, delete, or extend the selection through the real keyboard. Verify the resulting value/text afterward.',
    '- DOM code belongs inside page.evaluate. The surrounding JavaScript module runs in an isolated Node process.',
    '- The page/Playwright browser runs on the backend. Never create user files with page.evaluate Blob/object URLs, window.open, an HTML download attribute, or a page download click. Use file action=generate for new files or action=download for an existing HTTP(S) resource; only the returned current-session Artifact download URL proves delivery.',
    '- file action=read preserves the original registered attachment and derives semantic text/Office structure plus visual pages on demand. On the first content read, omit pages; request later 1-based pages explicitly.',
    '- User attachments are already registered by attachmentId. For an upload-only request, do not call file and do not reconstruct bytes, base64, Blob, File, or Buffer. Place and verify the editor caret first when needed, then call attachmentVault.setInputFiles(exactFileInputLocator, attachmentId); direct Locator/Page.setInputFiles(), FileChooser.setFiles(), and local paths are forbidden. Verify exactly one attachment remains at the requested destination.',
    '- Do not import modules or access Node globals, local files, environment variables, cookies, browser storage, or raw credential values. When the prompt supplies a credential reference, use only await credentialVault.fill(locator, ref); never read the filled field value or write credentials/references to outputs or logs.',
  ];
}

export function browserChatCodeRules(screenshotAvailable = true) {
  return [
    '- Use browserCode for live inspection and operation. It receives the real Playwright page/context and a persistent top-level-await JavaScript kernel: keep cells bounded, use top-level var or fresh names, and return compact evidence with nodeRepl.write(...). Once repeated rows or fields are exactly observed, update the deterministic batch in one bounded cell instead of spending one model cycle per item; wait for concrete DOM/navigation state instead of routine fixed waitForTimeout delays.',
    '- Before the first browser-changing cell of every new or resumed user request, use a separate read-only cell to return browser.user.openTabs(), page.url(), page.title(), and enough current AX/DOM/Playwright evidence chosen by the model. Confirm the active tab, its group, current page, and relevant rendered state before operating; never act directly from old conversation state.',
    '- Every browserCode result may include dependencyFailures, a once-only queue of request failures plus HTTP 408/429/5xx observed since the previous result, including failures completed between cells; inspect it before continuing. Operation/navigation/tab-change results also include actual.finalPage and direct incremental domChanges in actual.domChanges, but never an automatic axTree or a separate console payload. Page console errors appear once in domChanges.extra.errors. Use nodeRepl.write(...), not console.log, to return a code result. domChanges added/updated/removed describe only changes caused by that cell; extra carries mounted non-actionable changes and diagnostics; it is not a full snapshot. page.domSnapshot() returns one string containing surfaces/topSurfaceIds/surfaceStack plus an active-surface-scoped AX tree by default; never access surface properties on that string, and use await page.activeSurface() for structured surface fields. Pass { scope: "all" } only for background context. Keep DOM-only code inside page.evaluate, and do not access Node globals, files, environment variables, cookies, or browser storage.',
    '- Use exact tags, attributes, hierarchy, editability, mounted structure, surfaces, topSurfaceIds, and surfaceStack from the latest explicit read or domChanges to decide locators. Before every element action, every locator-defining role, name, text, test id, id, href, label, placeholder, or other attribute must appear verbatim in that latest evidence. If it does not, run a targeted read-only inspection first; never try a plausible selector as a probe. An explicit ARIA role overrides the native tag for role locators. Surface data is informational evidence of likely overlays, never an action permission boundary. Multiple IDs in topSurfaceIds are parallel visible candidates; parentId/depth and surfaceStack describe likely nesting, and visual overlap alone does not. Treat a newly opened nonmodal surface as a bounded transaction: before targeting outside it, verify that it closed; otherwise close it with an observed Done/Close control, its observed trigger, or Escape, and verify the transition with page.activeSurface(). Never translate or invent a selector and never infer a control type or interaction sequence from labels, appearance, or prior experience. Multiple bounded operations may run in the same cell, but use targeted Playwright reads before a dependent operation when an earlier action can change its target assumptions. For credentialVault.fill and every Playwright Locator/Page element action, choose a stable parent by data-testid, stable data-*, unique exact href/name, or another returned attribute. Page/Locator factories automatically remove hidden and zero-rectangle matches before count() or positional selection. Runtime applies target-style and hit-test checks followed by an action-specific Playwright trial to every remaining candidate; the Playwright trial result is authoritative for pointer actionability, while the custom hit test is supplemental diagnostics. It operates only when exactly one candidate passes all stages. An ancestor pointer-events:none alone does not reject a target. first(), last(), and nth() are allowed and their selected locator still receives the same runtime validation.',
    '- If no normal locator uniquely identifies the rendered target, inspect fresh DOM evidence and refine the locator scope. Code mode has no UID-click tool. For precise editing in an input, textarea, or contenteditable (including a frame locator), call targetPage.setTextSelection() on the Page that owns the locator, then edit through targetPage.keyboard in the same cell instead of coordinate clicking or directly mutating DOM text; verify the resulting value/text. After switching tabs or frames and before a clipboard or keyboard operation, re-establish and verify the intended editable target and focus.',
    '- Prefer normal Playwright actionability. When fresh DOM/Playwright evidence identifies one exact rendered target and proves that an overlay or backdrop is intentionally blocking the normal action, the model may use that unique Locator with force:true and must verify the resulting surface state afterward. Never use force for an ambiguous, hidden, detached, disabled, or unobserved target. After timeout, strict-mode failure, zero matches, or other actionability rejection, record the failed locator and actual count/error, then inspect incremental domChanges or explicitly run page.domSnapshot()/targeted Playwright reads and rebuild the locator. Do not describe a failure as transient without new proof, and do not omit the failed tool call from the final report after a successful retry; report every failed tool call in the final answer. Before claiming completion, perform a final read-only check of business success and page.activeSurface() and resolve or disclose any unexpected residual top surface. Do not bypass Playwright with DOM click, dispatchEvent, or script click.',
    screenshotAvailable
      ? '- For a Playwright-indescribable visual control only, emit a fresh viewport image with nodeRepl.emitImage(await page.screenshot({fullPage:false})) and end the cell; after the model sees that image, one coordinate/CUA action may be performed in the next cell. Full-page images are read-only, and a document, URL, viewport, zoom, or scroll-position change invalidates the image.'
      : '- Image and coordinate targeting are unavailable; use Playwright locators or DOM evidence.',
    '- For tabs/windows, use context.pages() or the available browser.tabs/browser.user/tab.playwright/tab.cua APIs. browser.user.openTabs() exposes active and group metadata for continuation. When given a credential reference, use credentialVault.fill(locator, ref) only; never read or output credential values or references.',
    '- File delivery is outside the backend test page. Do not use Blob/object URLs, window.open, HTML download attributes, or page download clicks to generate or claim a user file. Call file action=generate for new content or action=download for an existing HTTP(S) resource, and report success only with the returned Artifact download URL. file action=read preserves an attachment and returns semantic content plus on-demand visual pages. For an upload-only request do not read or reconstruct the file; use attachmentVault.setInputFiles(exactFileInputLocator, attachmentId), never Locator/Page.setInputFiles(), FileChooser.setFiles(), a local path, or a reconstructed payload.',
  ];
}

export function browserChatDomRules(screenshotAvailable = true) {
  return [
    '- Use inspect action="capture" mode="full" for the complete loaded semantic DOM. Later DOM interactions use only an exact dom-* ref exposed by this most recent snapshot. mode="text" is the reading view of all loaded text; mode="changes" contains only inter-action changes.',
    '- Every change follows OBSERVE -> ONE ACTION -> RE-OBSERVE -> VERIFY BUSINESS STATE. Confirm from a fresh inspect result the current page, [page-state].surfaces/topSurfaceIds/surfaceStack/activeSurface, expected result, exact target, and loading state. Surface fields and node surface markers are informational hints about likely overlays, not action restrictions. Treat a newly opened nonmodal surface as a bounded transaction: before targeting outside it, verify that it closed; otherwise close it using an observed Done/Close control, its observed trigger, or Escape and inspect again. Before claiming completion, perform a final read-only business-state and activeSurface check, resolve or disclose unexpected residual top surfaces, and report every failed tool call. If anything is uncertain or the interface may have changed, inspect again instead of acting.',
    '- Continue a paged frozen capture only with its exact nextCursor and the same mode. Never scroll for snapshot pagination. Use inspect action="search" to narrow the current baseline and action="httpRequests" for network evidence.',
    '- Every DOM interaction target contains only kind="ref" and the exact dom-* ref copied from the latest inspect result. It does not compare element text, attributes, or a semantic fingerprint. Do not send role, name, attributes, scope, target evidence, or a ref from conversation history. The backend checks current snapshot ownership, then relies on normal Playwright actionability. One interact call performs one operation. Its runtime verification result is a hard condition: verification.status="failed" means re-observe and continue from the actual current state, never claim completion or blindly repeat the operation.',
    '- Ordinary clicks still use Playwright actionability and covering-layer checks. Only when a fresh inspect proves the exact intended action is to close the currently visible overlay may you send action="click" with force=true. Force skips only actionability/cover checks; current snapshot ownership remains mandatory. Never use force to make an uncertain target succeed; inspect again immediately afterward.',
    screenshotAvailable
      ? '- No screenshot is attached automatically. When pixel evidence is necessary, call takeScreenshot with capture="viewport" and end that model step; after inspecting the returned image, use interact with either coordinates from that latest viewport screenshot or one current dom-* ref target, never both. Full-page and older screenshots are read-only evidence.'
      : '- Use interact with one current dom-* ref target; coordinate targeting is unavailable.',
    '- interact supports click, hover, drag, scrolling, type, editText, press, shortcuts, and selectOption. For an input, textarea, contenteditable, or iframe rich-text ref, use action="editText" with selection and operation="setSelection"|"insert"|"delete"|"replace". exactText selects one occurrence, start without end creates a caret, and start+end creates a range. The backend establishes the selection and applies the real-keyboard edit atomically. DOM targets scroll into view as needed; scroll the page only for confirmed lazy or virtual content.',
    '- For a native select, use interact action="selectOption" with its current dom-* ref and an exact option value or full label. For a container marked virtualized="possible", use selectOption with that container ref and an exact option value or full label; the backend scans the virtual list and clicks the unique mounted match. Do not manually page through a virtual list when this exact selection operation applies.',
    '- Use browser for navigation, waiting, listing tabs, and switching tabs. After an action may open a tab, list tabs before choosing the next target.',
    '- For a supplied credential reference, use interact action="type" with the current field dom-* ref only. Never place the secret in text, read it back, or expose the reference.',
  ];
}

export function browserActionRules(screenshotAvailable = true) {
  return [
    '- Before a bounded sequence of clicks, hovers, fills, presses, selections, drags, credential fills, or other state-changing element actions, use exact evidence that the model already inspected in a preceding explicit page.domSnapshot()/targeted read or in direct incremental domChanges. Every locator-defining role, name, text, test id, id, href, label, placeholder, or other attribute must appear verbatim in that evidence; if it does not, read first instead of trying a plausible selector. Multiple operations may run in one cell; use targeted Playwright reads before a dependent operation when an earlier action can change target assumptions.',
    '- Use exact current tags, attributes, hierarchy, editability, and mounted structure with targeted Playwright or read-only DOM inspection. Never translate or invent labels/selectors, and never infer control type, interaction sequence, or completion state from a label, appearance, or prior experience. Identify a stable parent using data-testid, stable data-*, a unique exact href/name, or another exact returned attribute. Page/Locator factories remove hidden and zero-rectangle matches from the rendered set before count() or positional selection. Every action then applies full actionability to the remaining candidates and proceeds only when exactly one candidate passes; otherwise narrow the locator.',
    '- If count() > 1, prefer a stronger stable attribute or parent scope, but first(), last(), and nth() are permitted when a positional choice is intentional. The resulting locator still passes normal visibility and actionability validation. If count() === 0 or current evidence does not identify the target, record the failed locator and actual count, obtain fresh explicit evidence, and rebuild the locator. Do not describe a failure as transient without new proof, and do not omit the failed tool call from the final report after a successful retry.',
    '- Runtime actionability normally rejects a target when it or any ancestor is display:none, visibility-hidden/collapsed, opacity-hidden, inert, disabled, detached, covered, or has no rendered rectangle. aria-hidden only changes accessibility exposure, so a target that is geometrically rendered and passes normal hit testing remains actionable; use an exact current DOM locator when a role locator omits it. For pointer actions runtime checks the target final computed pointer-events value, performs a real hit test, and runs an action-specific Playwright trial for every visible candidate; an ancestor pointer-events:none alone is not a rejection. If fresh evidence identifies one exact rendered target and proves an overlay or backdrop is intentionally blocking it, use that unique Locator with force:true and verify the surface closed or changed afterward. Never force an ambiguous, visually hidden, detached, disabled, or unobserved target, and never fall back to DOM element.click(), dispatchEvent(), or script click.',
    '- CUA or coordinate clicking is allowed only for a special visual control that Playwright cannot describe. Use two separate model steps: first end a browserCode cell after emitting a fresh viewport screenshot, then inspect the returned image, confirm the intended point is not obscured, and perform one coordinate click in the next browserCode cell. Same-cell screenshot-and-click is forbidden, and the runtime rejects stale evidence after a document, URL, viewport, zoom, or scroll-position change.',
    '- Use stable Playwright locators for semantic elements. For native HTML <select>, call locator.selectOption(...) directly.',
    '- A browserCode cell may contain bounded read-only inspection and multiple bounded state-changing operations.',
    '- After the operation sequence inspect its direct result and incremental domChanges. Treat every newly opened nonmodal surface as a bounded transaction: before targeting outside it, verify that it closed; otherwise close it with an observed Done/Close control, its observed trigger, or Escape and verify via page.activeSurface(). When evidence is insufficient, explicitly write a read-only page.domSnapshot(), URL, DOM, value, text, or network check. Before claiming completion, make a final read-only check of business success and page.activeSurface(), resolve or disclose unexpected residual top surfaces, and report every failed tool call. Playwright delivery alone does not prove business success, but no specific verification helper is mandatory.',
    '- Use scrolling only for lazy-loaded, virtualized, or viewport-created content.',
    screenshotAvailable
      ? '- Use page.mouse coordinates only in the browserCode cell after the model has received and inspected a fresh viewport screenshot from the previous cell.'
      : '- Image-coordinate targeting is unavailable; use locators or DOM inspection.',
  ];
}

export function browserContextLine() {
  return 'No page state is preloaded. On every new or resumed browser request, first use a read-only browserCode cell to inspect existing tabs/groups, the active page identity, and enough current AX/DOM/Playwright evidence chosen by the model before changing the browser.';
}

export function screenshotObservationRule(screenshotAvailable = true) {
  return screenshotAvailable
    ? '- Final page identity is attached automatically. Actual browser operations, navigation, and tab changes also attach direct incremental domChanges; page console errors appear once in domChanges.extra.errors, with no separate console payload. Results never include an automatic axTree, and pure successful reads attach no automatic DOM content. No screenshot is attached automatically. When AX, DOM, or pixel evidence is necessary, write the corresponding read explicitly in browserCode; emit pixels with await nodeRepl.emitImage(await page.screenshot({ fullPage: false })) so the image becomes visible to the model in the next model step.'
    : '- No image observation is available. Use browserCode for inspection and browser operations.';
}
