import { z } from 'zod';
import { defineCapabilityInput, defineCapabilityTool, normalizeBoundedInteger, type CapabilityExecutionContext, type CapabilityHealth, type CapabilityManifest, type CapabilityProvider, type CapabilityRunContext } from '@webpilot/capability-sdk';
import { dataRuntimeSkill } from './runtime-skill.js'; import { dataCapabilitySettings } from './settings.js';
export * from './runtime-skill.js'; export * from './settings.js';

export const dataCapabilityToolNames = Object.freeze({ data: 'data' } as const);
export type DataColumn = { name: string; type?: string; nullable?: boolean; description?: string };
export type DataTable = { name: string; description?: string; columns: DataColumn[] };
export type DataQueryResult = { columns: string[]; rows: Array<Record<string, unknown>>; rowCount: number; truncated: boolean; elapsedMs?: number };
export interface AgentDataSource {
  id: string; name: string; dialect?: string; readOnly?: boolean;
  schema(context: CapabilityExecutionContext): Promise<DataTable[]>;
  query(statement: string, parameters: unknown[], options: { maxRows: number; allowWrite: boolean }, context: CapabilityExecutionContext): Promise<DataQueryResult>;
  health?(): Promise<CapabilityHealth>; dispose?(): Promise<void>;
}
export interface DataSourceRegistry { list(): readonly AgentDataSource[]; get(id: string): AgentDataSource | undefined; }
export function createDataSourceRegistry(sources: readonly AgentDataSource[]): DataSourceRegistry { const byId = new Map<string, AgentDataSource>(); for (const source of sources) { if (!source.id.trim()) throw new Error('Data source id is required.'); if (byId.has(source.id)) throw new Error(`Duplicate data source id: ${source.id}.`); byId.set(source.id, source); } return Object.freeze({ list: () => Object.freeze([...byId.values()]), get: (id: string) => byId.get(id) }); }
export function isReadOnlyStatement(statement: string) { const normalized = statement.replace(/^\s*(?:--[^\n]*\n|\/\*[\s\S]*?\*\/\s*)*/g, '').trim().toLowerCase(); return /^(select|with|explain|show|describe|pragma)\b/.test(normalized) && !/\b(insert|update|delete|merge|alter|drop|create|truncate|grant|revoke|replace|vacuum|attach|detach)\b/.test(normalized); }

const parser = z.object({ action: z.enum(['sources', 'schema', 'query']), reason: z.string().trim().min(1).max(300), sourceId: z.string().trim().min(1).max(200).optional(), statement: z.string().trim().min(1).max(100_000).optional(), parameters: z.array(z.unknown()).max(500).optional(), maxRows: z.number().int().min(1).max(10000).optional() }).strict().superRefine((input, context) => { if ((input.action === 'schema' || input.action === 'query') && !input.sourceId) context.addIssue({ code: 'custom', path: ['sourceId'], message: `${input.action} requires sourceId.` }); if (input.action === 'query' && !input.statement) context.addIssue({ code: 'custom', path: ['statement'], message: 'query requires statement.' }); });
export type DataToolInput = z.infer<typeof parser>;
export const dataToolInput = defineCapabilityInput<DataToolInput>(z.toJSONSchema(parser) as Readonly<Record<string, unknown>>, (value) => parser.parse(value));
export const dataCapabilityManifest = Object.freeze({ schemaVersion: 1, id: 'com.webpilot.data', name: 'Data', version: '0.1.0', description: 'Discover schemas and execute bounded queries against host-configured structured data sources.', permissions: ['data:read', 'data:write'], runtimeRequirements: { node: '>=22.16' }, configuration: { settings: dataCapabilitySettings }, skills: [dataRuntimeSkill] } satisfies CapabilityManifest);

export function createDataTool(registry: DataSourceRegistry, configuration: CapabilityRunContext['configuration']) { return defineCapabilityTool<DataToolInput, unknown>({
  name: 'data', description: 'List structured data sources, inspect an exact schema, or run a bounded parameterized query. Read-only is the default.', input: dataToolInput, policy: { concurrency: 'serial', concurrencyGroup: 'structured-data', permissions: dataCapabilityManifest.permissions },
  async execute(input, context) { try { if (input.action === 'sources') return { ok: true, summary: 'Configured data sources.', data: registry.list().map(({ id, name, dialect, readOnly }) => ({ id, name, dialect, readOnly: readOnly !== false })) }; const source = registry.get(input.sourceId!); if (!source) return { ok: false, error: { code: 'data-source-not-found', message: `Unknown data source: ${input.sourceId}.` } }; if (input.action === 'schema') return { ok: true, summary: `${source.name} schema.`, data: await source.schema(context) }; const readOnly = isReadOnlyStatement(input.statement!); const allowWrite = configuration.AGENT_DATA_ALLOW_WRITES === 'true' && source.readOnly === false; if (!readOnly && !allowWrite) return { ok: false, error: { code: 'data-write-disabled', message: 'This statement is not read-only and data writes are disabled.' } }; const result = await source.query(input.statement!, input.parameters || [], { maxRows: input.maxRows || normalizeBoundedInteger(configuration.AGENT_DATA_MAX_ROWS, 500, 1, 10000), allowWrite }, context); return { ok: true, summary: `Data query returned ${result.rowCount} row(s)${result.truncated ? ' (truncated)' : ''}.`, data: result }; } catch (error) { return { ok: false, error: { code: 'data-operation-failed', message: error instanceof Error ? error.message : String(error) } }; } },
}); }
export function createDataCapability(options: { createRegistry(context: CapabilityRunContext): DataSourceRegistry | Promise<DataSourceRegistry> }): CapabilityProvider { return { manifest: dataCapabilityManifest, async createRuntime(context) { const registry = await options.createRegistry(context); return { tools: Object.freeze({ data: createDataTool(registry, context.configuration) }), health: async () => { const statuses = await Promise.all(registry.list().map((source) => source.health?.() || Promise.resolve({ status: 'healthy' as const }))); return statuses.some((item) => item.status === 'unhealthy') ? { status: 'degraded', message: 'One or more data sources are unhealthy.' } : { status: 'healthy' }; }, dispose: async () => { await Promise.allSettled(registry.list().map((source) => source.dispose?.())); } }; } }; }
