import { z } from 'zod';
import { defineCapabilityInput, defineCapabilityTool, normalizeBoundedInteger, type CapabilityExecutionContext, type CapabilityHealth, type CapabilityManifest, type CapabilityProvider, type CapabilityRunContext } from '@webpilot/capability-sdk';
import { mediaRuntimeSkill } from './runtime-skill.js'; import { mediaCapabilitySettings } from './settings.js';
export * from './runtime-skill.js'; export * from './settings.js';

export const mediaCapabilityToolNames = Object.freeze({ media: 'media' } as const);
export type MediaArtifact = { artifactId: string; mediaType?: string; downloadUrl?: string; description?: string };
export interface MediaOperations {
  inspect(sourceRef: string, context: CapabilityExecutionContext): Promise<unknown>;
  extractFrames?(input: { sourceRef: string; intervalSeconds?: number; maxFrames: number }, context: CapabilityExecutionContext): Promise<MediaArtifact[]>;
  ocr?(input: { sourceRef: string; language?: string }, context: CapabilityExecutionContext): Promise<unknown>;
  transcribe?(input: { sourceRef: string; language?: string; timestamps: boolean }, context: CapabilityExecutionContext): Promise<unknown>;
  generateImage?(input: { prompt: string; width?: number; height?: number }, context: CapabilityExecutionContext): Promise<MediaArtifact[]>;
  health?(): Promise<CapabilityHealth>; dispose?(): Promise<void>;
}
const parser = z.object({ action: z.enum(['inspect', 'extractFrames', 'ocr', 'transcribe', 'generateImage']), reason: z.string().trim().min(1).max(300), sourceRef: z.string().trim().min(1).max(8_000).optional(), prompt: z.string().trim().min(1).max(20_000).optional(), language: z.string().trim().min(2).max(40).optional(), timestamps: z.boolean().optional(), intervalSeconds: z.number().min(0.1).max(3600).optional(), maxFrames: z.number().int().min(1).max(60).optional(), width: z.number().int().min(64).max(4096).optional(), height: z.number().int().min(64).max(4096).optional() }).strict().superRefine((input, context) => { if (input.action !== 'generateImage' && !input.sourceRef) context.addIssue({ code: 'custom', path: ['sourceRef'], message: `${input.action} requires sourceRef.` }); if (input.action === 'generateImage' && !input.prompt) context.addIssue({ code: 'custom', path: ['prompt'], message: 'generateImage requires prompt.' }); });
export type MediaToolInput = z.infer<typeof parser>; export const mediaToolInput = defineCapabilityInput<MediaToolInput>(z.toJSONSchema(parser) as Readonly<Record<string, unknown>>, (value) => parser.parse(value));
export const mediaCapabilityManifest = Object.freeze({ schemaVersion: 1, id: 'com.webpilot.media', name: 'Media', version: '0.1.0', description: 'Inspect and transform images, audio, video, and scanned content through host-selected providers.', permissions: ['artifact:read', 'artifact:write', 'media:process', 'model:media'], runtimeRequirements: { node: '>=22.16' }, configuration: { settings: mediaCapabilitySettings }, skills: [mediaRuntimeSkill] } satisfies CapabilityManifest);

export function createMediaTool(operations: MediaOperations, configuration: CapabilityRunContext['configuration']) { return defineCapabilityTool<MediaToolInput, unknown>({
  name: 'media', description: 'Inspect media, extract bounded video frames, run OCR or transcription, or generate a clearly identified image artifact.', input: mediaToolInput, policy: { concurrency: 'serial', concurrencyGroup: 'media-processing', permissions: mediaCapabilityManifest.permissions },
  async execute(input, context) { try { let data: unknown; if (input.action === 'inspect') data = await operations.inspect(input.sourceRef!, context); else if (input.action === 'extractFrames') { if (!operations.extractFrames) return { ok: false, error: { code: 'media-operation-unavailable', message: 'Frame extraction is not configured.' } }; data = await operations.extractFrames({ sourceRef: input.sourceRef!, intervalSeconds: input.intervalSeconds, maxFrames: Math.min(input.maxFrames || normalizeBoundedInteger(configuration.AGENT_MEDIA_MAX_FRAMES, 12, 1, 60), normalizeBoundedInteger(configuration.AGENT_MEDIA_MAX_FRAMES, 12, 1, 60)) }, context); } else if (input.action === 'ocr') { if (!operations.ocr) return { ok: false, error: { code: 'media-operation-unavailable', message: 'OCR is not configured.' } }; data = await operations.ocr({ sourceRef: input.sourceRef!, language: input.language }, context); } else if (input.action === 'transcribe') { if (!operations.transcribe) return { ok: false, error: { code: 'media-operation-unavailable', message: 'Transcription is not configured.' } }; data = await operations.transcribe({ sourceRef: input.sourceRef!, language: input.language, timestamps: input.timestamps !== false }, context); } else { if (!operations.generateImage) return { ok: false, error: { code: 'media-operation-unavailable', message: 'Image generation is not configured.' } }; data = await operations.generateImage({ prompt: input.prompt!, width: input.width, height: input.height }, context); } const artifacts = Array.isArray(data) ? data.filter((item): item is MediaArtifact => Boolean(item) && typeof item === 'object' && 'artifactId' in item) : []; return { ok: true, summary: `Media ${input.action} completed.`, data, content: artifacts.map((artifact) => artifact.mediaType?.startsWith('image/') ? { type: 'image' as const, artifactId: artifact.artifactId, mediaType: artifact.mediaType } : { type: 'artifact' as const, artifactId: artifact.artifactId, mediaType: artifact.mediaType, downloadUrl: artifact.downloadUrl }) }; } catch (error) { return { ok: false, error: { code: 'media-operation-failed', message: error instanceof Error ? error.message : String(error), retryable: false } }; } },
}); }
export function createMediaCapability(options: { createOperations(context: CapabilityRunContext): MediaOperations | Promise<MediaOperations> }): CapabilityProvider { return { manifest: mediaCapabilityManifest, async createRuntime(context) { const operations = await options.createOperations(context); return { tools: Object.freeze({ media: createMediaTool(operations, context.configuration) }), health: () => operations.health?.() || Promise.resolve({ status: 'healthy' }), dispose: () => operations.dispose?.() || Promise.resolve() }; } }; }
