import { spawn } from 'node:child_process'; import { mkdtemp, readdir, rm } from 'node:fs/promises'; import path from 'node:path'; import os from 'node:os';
import { createMediaCapability, type MediaArtifact, type MediaOperations } from './index.js'; import type { CapabilityExecutionContext, CapabilityRunContext } from '@webpilot/capability-sdk';

async function run(executable: string, args: string[], timeoutMs: number, context: CapabilityExecutionContext) { return new Promise<{ stdout: string; stderr: string }>((resolve, reject) => { const child = spawn(executable, args, { shell: false, windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'] }); let stdout = ''; let stderr = ''; child.stdout.on('data', (chunk) => { stdout = (stdout + String(chunk)).slice(-100_000); }); child.stderr.on('data', (chunk) => { stderr = (stderr + String(chunk)).slice(-100_000); }); const stop = () => child.kill('SIGKILL'); const timer = setTimeout(stop, timeoutMs); timer.unref?.(); const onAbort = () => stop(); context.abortSignal?.addEventListener('abort', onAbort, { once: true }); child.once('error', reject); child.once('close', (code) => { clearTimeout(timer); context.abortSignal?.removeEventListener('abort', onAbort); if (code === 0) resolve({ stdout, stderr }); else reject(new Error(stderr || `Media process exited with code ${code}.`)); }); }); }
export function createFfmpegMediaOperations(input: { ffmpegPath: string; resolveSource(sourceRef: string, context: CapabilityExecutionContext): Promise<string>; publishArtifact(filePath: string, context: CapabilityExecutionContext): Promise<MediaArtifact>; timeoutMs?: number; ocr?: MediaOperations['ocr']; transcribe?: MediaOperations['transcribe']; generateImage?: MediaOperations['generateImage'] }): MediaOperations {
  return {
    async inspect(sourceRef, context) { const source = await input.resolveSource(sourceRef, context); try { const result = await run(input.ffmpegPath, ['-hide_banner', '-i', source, '-f', 'null', '-'], input.timeoutMs || 120_000, context); return { sourceRef, inspected: true, probe: result.stderr.split(source).join(sourceRef).slice(0, 20_000) }; } catch (error) { const message = error instanceof Error ? error.message : String(error); if (/Duration:|Stream #/i.test(message)) return { sourceRef, inspected: true, probe: message.split(source).join(sourceRef).slice(0, 20_000) }; throw error; } },
    async extractFrames(request, context) { const source = await input.resolveSource(request.sourceRef, context); const directory = await mkdtemp(path.join(os.tmpdir(), 'webpilot-media-')); try { const pattern = path.join(directory, 'frame-%04d.jpg'); const filter = request.intervalSeconds ? `fps=1/${request.intervalSeconds}` : `thumbnail=${Math.max(1, request.maxFrames)}`; await run(input.ffmpegPath, ['-hide_banner', '-i', source, '-vf', filter, '-frames:v', String(request.maxFrames), '-q:v', '2', pattern], input.timeoutMs || 120_000, context); const files = (await readdir(directory)).filter((name) => name.endsWith('.jpg')).sort().slice(0, request.maxFrames); return await Promise.all(files.map((name) => input.publishArtifact(path.join(directory, name), context))); } finally { await rm(directory, { recursive: true, force: true }).catch(() => undefined); } },
    ocr: input.ocr, transcribe: input.transcribe, generateImage: input.generateImage,
    async health() { return input.ffmpegPath ? { status: 'healthy' } : { status: 'needs-runtime', message: 'FFmpeg path is not configured.' }; },
  };
}
export function createNodeMediaCapability(input: { createOperations(context: CapabilityRunContext): MediaOperations | Promise<MediaOperations> }) { return createMediaCapability(input); }
